# Test derivation to verify Nix uses local files as FOD substitutes
# Run this on Prometheus to ensure files are found in Nix store without downloading

{ pkgs ? import <nixpkgs> {} }:

let
  # These are the actual store paths on Prometheus
  # Generated by: nix-store --add /home/li/.local/share/prometheus-llama/models/...
  deepseekShard1Path = /nix/store/0lcmh5j1b246ylb9j34vifja2znvv0hl-DeepSeek-R1-Distill-Llama-70B-Q8_0-00001-of-00002.gguf;
  deepseekShard2Path = /nix/store/b3wimrs32qmbwz0jlwrl1iagbd98gqlb-DeepSeek-R1-Distill-Llama-70B-Q8_0-00002-of-00002.gguf;
  
  # Test 1: Verify local files exist in Nix store
  testLocalFiles = pkgs.stdenv.mkDerivation {
    name = "test-local-files";
    
    buildCommand = ''
      echo "=== Test: Local Files in Nix Store ==="
      
      echo ""
      echo "Checking DeepSeek Shard 1..."
      if [ -f "${deepseekShard1Path}" ]; then
        echo "✓ Shard 1 exists at: ${deepseekShard1Path}"
        echo "  Size: $(stat -c%s ${deepseekShard1Path}) bytes"
        echo "  Hash: $(nix hash file --type sha256 ${deepseekShard1Path})"
      else
        echo "✗ Shard 1 NOT found at: ${deepseekShard1Path}"
        exit 1
      fi
      
      echo ""
      echo "Checking DeepSeek Shard 2..."
      if [ -f "${deepseekShard2Path}" ]; then
        echo "✓ Shard 2 exists at: ${deepseekShard2Path}"
        echo "  Size: $(stat -c%s ${deepseekShard2Path}) bytes"
        echo "  Hash: $(nix hash file --type sha256 ${deepseekShard2Path})"
      else
        echo "✗ Shard 2 NOT found at: ${deepseekShard2Path}"
        exit 1
      fi
      
      echo ""
      echo "=== All local files found in Nix store ==="
      
      # Create output
      mkdir -p $out
      echo "SUCCESS: All files found" > $out/test-result
    '';
  };
  
  # Test 2: Verify fetchurl uses local files (FOD substitution)
  # This will try to fetch from URL, but if the file exists in store with correct hash,
  # Nix will use it as a substitute without downloading
  testFetchurlSubstitution = pkgs.stdenv.mkDerivation {
    name = "test-fetchurl-substitution";
    
    src = pkgs.fetchurl {
      url = "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Llama-70B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-70B-Q8_0-00001-of-00002.gguf";
      sha256 = "sha256-q2mbEa0CzwJznepf5fZrZOtRQMvfwRBS68In/bKlmsk=";
    };
    
    buildCommand = ''
      echo "=== Test: FOD Substitution ==="
      
      echo ""
      echo "Checking if fetchurl used local file..."
      if [ -f "$src" ]; then
        echo "✓ Source exists at: $src"
        echo "  Size: $(stat -c%s $src) bytes"
        
        # Verify hash matches expected
        ACTUAL_HASH=$(nix hash file --type sha256 $src)
        EXPECTED_HASH="sha256-q2mbEa0CzwJznepf5fZrZOtRQMvfwRBS68In/bKlmsk="
        
        if [ "$ACTUAL_HASH" = "$EXPECTED_HASH" ]; then
          echo "✓ Hash matches expected: $ACTUAL_HASH"
        else
          echo "✗ Hash mismatch!"
          echo "  Expected: $EXPECTED_HASH"
          echo "  Actual: $ACTUAL_HASH"
          exit 1
        fi
      else
        echo "✗ Source NOT found"
        exit 1
      fi
      
      echo ""
      echo "=== FOD substitution successful ==="
      
      # Create output
      mkdir -p $out
      cp $src $out/test.gguf
      echo "SUCCESS: FOD substitution worked" > $out/test-result
    '';
  };
  
  # Test 3: Merge DeepSeek shards (simulating actual model building)
  testMergeShards = pkgs.runCommand "test-merge-shards"
    { nativeBuildInputs = [ pkgs.coreutils ]; }
    ''
      echo "=== Test: Merge Shards ==="
      
      echo ""
      echo "Merging DeepSeek shards..."
      cat ${deepseekShard1Path} ${deepseekShard2Path} > $out/merged.gguf
      
      echo "Merged file created at: $out/merged.gguf"
      echo "  Size: $(stat -c%s $out/merged.gguf) bytes"
      echo "  Hash: $(nix hash file --type sha256 $out/merged.gguf)"
      
      echo ""
      echo "=== Shard merge successful ==="
    '';

in {
  testLocalFiles = testLocalFiles;
  testFetchurlSubstitution = testFetchurlSubstitution;
  testMergeShards = testMergeShards;
  
  # Default test
  default = testFetchurlSubstitution;
}
